name: Pull Request Workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  unit_tests:
    runs-on: ubuntu-16.04

    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: database
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      SETTINGS_DATABASE_ENDPOINT: postgres://user:password@localhost:5432/database

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.6

      - name: Install bundle gem
        run: gem install bundler:2.1.4

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake unit_tests

  code_quality:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.6
 
      - name: Rubocop check
        run: gem install rubocop && rubocop
